// Package sched provides a simple in-process scheduler for recurring tasks
// driven by fixed time intervals (as opposed to cron expressions — see the
// top-level cog/sched package for cron-based scheduling).
//
// Each task runs in its own goroutine, so a slow invocation never blocks the
// scheduler or delays sibling tasks. The timer is reset immediately after
// dispatch, preserving a fixed cadence (start-to-start) regardless of task
// duration.
//
// Features:
//   - Interval: frequency between invocations (time.Duration).
//   - StartAfter: delay the first firing until a specific time.
//   - RunOnce: execute exactly once, then auto-remove.
//   - RunSingleInstance: skip overlapping invocations when the previous one
//     is still running (uses sync.Mutex.TryLock).
//   - ErrFunc: callback for errors (including recovered panics).
//   - Panic recovery: a panicking task is captured and routed to ErrFunc.
//
// All IDs are int64, generated by cam/idgen.Mist. The scheduler is terminal
// after Stop — subsequent Add/AddWithID return ErrSchedulerStop.
//
// Usage:
//
//	s := sched.New()
//	defer s.Stop()
//
//	id, err := s.Add(&sched.Task{
//	    Interval: 30 * time.Second,
//	    TaskFunc: func() error { /* ... */ return nil },
//	    ErrFunc:  func(e error) { log.Print(e) },
//	})
//
// For cron-expression scheduling, use the top-level cog/sched package instead.
package sched
