// Package sched provides a simple in-process scheduler for recurring tasks
// driven by fixed time intervals (as opposed to cron expressions — see the
// top-level cog/sched package for that).
//
// Each task runs in its own goroutine, so a slow invocation never blocks the
// scheduler or delays sibling tasks. For tasks that may occasionally exceed
// their interval, RunSingleInstance skips overlapping invocations instead of
// piling up goroutines.
//
// Design notes:
//   - IDs are int64, generated by cam/idgen.Mist. All of Add / AddWithID /
//     Del / Lookup / Tasks use int64 consistently.
//   - The per-task mutex (task.mu) protects timer/cancel lifecycle so that
//     Del and the timer callback cannot race on timer.Reset.
//   - Stop is terminal: any subsequent Add/AddWithID returns ErrSchedulerStopped.
package sched

import (
	"context"
	"errors"
	"fmt"
	"sync"
	"sync/atomic"
	"time"

	"ojv/cog/cam/idgen"
)

// TaskFunc is the function executed by a scheduled task. Returning a non-nil
// error routes it to the task's ErrFunc (if set).
type TaskFunc func() error

// ErrFunc handles errors returned by TaskFunc. If nil, errors are silently
// ignored. Panics recovered from TaskFunc are also routed here as errors.
type ErrFunc func(error)

// Task describes a recurring job submitted to a Scheduler. Public fields are
// configured by the caller before Add/AddWithID; internal fields are managed
// by the Scheduler.
type Task struct {
	// Interval is the frequency at which the task executes. Must be > 0.
	// The first execution happens after one Interval (plus any StartAfter
	// delay); subsequent executions are spaced by Interval.
	Interval time.Duration

	// StartAfter delays the first execution until the specified time.
	// If zero or in the past, only the normal Interval wait applies.
	StartAfter time.Time

	// RunOnce executes the task exactly once, then auto-removes it.
	RunOnce bool

	// RunSingleInstance skips an invocation when the previous one is still
	// running. Useful for tasks that may occasionally exceed Interval.
	RunSingleInstance bool

	// TaskFunc is the function to execute. Must be non-nil.
	TaskFunc TaskFunc

	// ErrFunc is invoked with the error (or recovered panic) when TaskFunc
	// returns a non-nil error or panics. Optional.
	ErrFunc ErrFunc

	// --- internal (managed by Scheduler) ---

	id     int64
	timer  *time.Timer
	ctx    context.Context
	cancel context.CancelFunc

	// mu protects timer/cancel/cancelled against concurrent Del and the
	// timer callback. Distinct from runMu (which only guards single-instance
	// execution).
	mu        sync.Mutex
	cancelled bool

	// runMu serializes RunSingleInstance invocations.
	runMu sync.Mutex
}

// Scheduler manages a set of recurring interval-based tasks.
type Scheduler struct {
	mu      sync.RWMutex
	tasks   map[int64]*Task
	mist    *idgen.Mist
	stopped atomic.Bool
}

// Sentinel errors returned by the scheduler.
var (
	ErrIDInUse       = errors.New("task ID already in use")
	ErrSchedulerStop = errors.New("scheduler already stopped")
)

// New creates a new Scheduler.
func New() *Scheduler {
	return &Scheduler{
		tasks: make(map[int64]*Task),
		mist:  idgen.NewMist(),
	}
}

// Add registers a task with an auto-generated ID and starts it.
// Returns the generated ID.
func (s *Scheduler) Add(t *Task) (int64, error) {
	if err := validate(t); err != nil {
		return 0, err
	}
	// Loop instead of recurse: avoids stack growth on the (astronomically
	// unlikely) repeat collision and is clearer.
	for {
		id := s.mist.Generate()
		err := s.AddWithID(id, t)
		if err == nil {
			return id, nil
		}
		if !errors.Is(err, ErrIDInUse) {
			return 0, err
		}
	}
}

// AddWithID registers a task with a caller-chosen int64 ID and starts it.
// Returns ErrIDInUse if the ID is already taken, or ErrSchedulerStop if the
// scheduler has been stopped.
func (s *Scheduler) AddWithID(id int64, t *Task) error {
	if err := validate(t); err != nil {
		return err
	}
	if s.stopped.Load() {
		return ErrSchedulerStop
	}

	s.mu.Lock()
	defer s.mu.Unlock()
	// double-check under lock to avoid race with Stop()
	if s.stopped.Load() {
		return ErrSchedulerStop
	}
	if _, ok := s.tasks[id]; ok {
		return ErrIDInUse
	}

	// Initialize task internal state. We do NOT clone the task: the caller's
	// *Task is stored directly (the original cor/tasks cloned to paper over
	// shared-timer bugs; with proper locking cloning is unnecessary and only
	// adds surprise — mutations to the caller's struct after Add would not
	// affect the scheduled copy).
	t.id = id
	t.ctx, t.cancel = context.WithCancel(context.Background())
	s.tasks[id] = t
	s.scheduleTask(t)
	return nil
}

func validate(t *Task) error {
	if t.TaskFunc == nil {
		return errors.New("task function cannot be nil")
	}
	if t.Interval <= 0 {
		return errors.New("task interval must be positive")
	}
	return nil
}

// Del removes a task by ID and stops future invocations. A currently running
// invocation is allowed to finish (Del does not interrupt an in-flight task).
// Missing IDs are a no-op.
func (s *Scheduler) Del(id int64) {
	s.mu.Lock()
	t, ok := s.tasks[id]
	if ok {
		delete(s.tasks, id)
	}
	s.mu.Unlock()

	if !ok {
		return
	}
	// Tear down under task.mu so that a concurrent timer callback observes
	// cancelled=true and skips its timer.Reset. cancel/timer.Stop are safe
	// to call from here (outside scheduler.mu to avoid holding two locks).
	t.mu.Lock()
	defer t.mu.Unlock()
	t.cancelled = true
	if t.cancel != nil {
		t.cancel()
	}
	if t.timer != nil {
		t.timer.Stop()
	}
}

// Lookup returns the task with the given ID, or an error if not found.
// The returned task is the live internal pointer; treat it as read-only.
func (s *Scheduler) Lookup(id int64) (*Task, error) {
	s.mu.RLock()
	defer s.mu.RUnlock()
	t, ok := s.tasks[id]
	if !ok {
		return nil, fmt.Errorf("task %d not found", id)
	}
	return t, nil
}

// Tasks returns a snapshot copy of all registered tasks keyed by ID.
// The returned map is safe for the caller to mutate.
func (s *Scheduler) Tasks() map[int64]*Task {
	s.mu.RLock()
	defer s.mu.RUnlock()
	m := make(map[int64]*Task, len(s.tasks))
	for k, v := range s.tasks {
		m[k] = v
	}
	return m
}

// Stop cancels and removes all tasks. After Stop the scheduler is terminal:
// any subsequent Add/AddWithID returns ErrSchedulerStop.
func (s *Scheduler) Stop() {
	s.mu.Lock()
	s.stopped.Store(true)
	tasks := s.tasks
	s.tasks = make(map[int64]*Task)
	s.mu.Unlock()

	for _, t := range tasks {
		t.mu.Lock()
		t.cancelled = true
		if t.cancel != nil {
			t.cancel()
		}
		if t.timer != nil {
			t.timer.Stop()
		}
		t.mu.Unlock()
	}
}

// scheduleTask arms the first firing. The first execution happens after
// (delay-until-StartAfter clamped to >=0) + one Interval, matching the
// documented "wait one interval, then run" semantics.
func (s *Scheduler) scheduleTask(t *Task) {
	delay := time.Until(t.StartAfter)
	if delay < 0 {
		delay = 0
	}
	delay += t.Interval

	t.mu.Lock()
	defer t.mu.Unlock()
	t.timer = time.AfterFunc(delay, func() { s.execTask(t) })
}

// execTask is the timer callback. It spawns the user function in its own
// goroutine (so the timer can be reset immediately to keep a fixed cadence),
// then reschedules the next firing.
func (s *Scheduler) execTask(t *Task) {
	t.mu.Lock()
	if t.cancelled {
		t.mu.Unlock()
		return
	}
	t.mu.Unlock()

	// Run the user function in a goroutine so a slow task does not shift
	// the cadence of subsequent firings.
	go func() {
		if t.RunSingleInstance {
			if !t.runMu.TryLock() {
				return
			}
			defer t.runMu.Unlock()
		}
		err := runRecover(t)
		if err != nil && t.ErrFunc != nil {
			t.ErrFunc(err)
		}
		if t.RunOnce {
			s.Del(t.id)
		}
	}()

	// Reschedule the next firing. Re-check cancelled under the lock so that a
	// concurrent Del cannot leave a reset timer dangling.
	if !t.RunOnce {
		t.mu.Lock()
		defer t.mu.Unlock()
		if !t.cancelled && t.timer != nil {
			t.timer.Reset(t.Interval)
		}
	}
}

// runRecover executes TaskFunc with panic recovery, returning either the
// function's own error or a synthesized error describing the panic.
func runRecover(t *Task) (err error) {
	defer func() {
		if r := recover(); r != nil {
			err = fmt.Errorf("sched: task %d panic: %v", t.id, r)
		}
	}()
	return t.TaskFunc()
}
